Acmp0013
DenMazila/java-learning pull request #3
Opened 2022-03-30 19:53 UTC by DenMazila

2022-03-30 20:28 UTC, vladimirshefer requested changes

2022-03-30 20:28 UTC, vladimirshefer commented on src/main/java/com/github/denmazila/java_learning/acmp/task0013/Main.java
> +    public static int[] integerToArrayConversionSuggestedTumber(int suggestedTumber) {
Tumber - опечатка?
наверное ты хотел написать Number

2022-03-30 20:28 UTC, vladimirshefer commented on src/main/java/com/github/denmazila/java_learning/acmp/task0013/Main.java
> +                + " " + numberOfIndirectMatches(Main.integerToArrayConversionHiddenNumber(hiddenNumber), integerToArrayConversionSuggestedTumber(suggestedTumber)));
слишком длинные строчки.
плюс вы вызываешь одну и ту же функцию два раза с одним и тем же аргументом.
имеет смысл вынести в переменную
что-то типа
```java
int[] hidden = Main.integerToArrayConversionHiddenNumber(hiddenNumber);
int[] suggested = integerToArrayConversionSuggestedTumber(suggestedTumber);
sout(numberOfExactMatches(hidden, suggested) + " " + numberOfIndirectMatches(hidden, suggested))
```

2022-03-30 20:28 UTC, vladimirshefer commented on src/main/java/com/github/denmazila/java_learning/java_learning.iml
> +<?xml version="1.0" encoding="UTF-8"?>
добавь этот файл в .gitignore - он не нужен в репозиторий
```.gitignore
*.iml
*.ipr
```

2022-03-30 20:28 UTC, vladimirshefer commented on src/test/java/com/github/denmazila/java_learning/acmp/task0013/MainTest.java
> +}
красный знак "стоп" значит что в конце файла нет пустой строчки.
хорошим тоном является оставлять пустую строчку в конце файла, если это возможно. (если интересно почему то [вот ссылка](http://ruby.qkspace.com/ruby-zachem-pustaya-stroka-v-kontse-fayla))

2022-03-30 20:28 UTC, vladimirshefer commented on src/test/java/com/github/denmazila/java_learning/acmp/task0013/MainTest.java
> +}
в настройках идеи потом можно сделать так чтобы она автоматически ставила пустую строку в конец при форматировании файла

2022-03-31 16:53 UTC, DenMazila commented on src/test/java/com/github/denmazila/java_learning/acmp/task0013/MainTest.java
> +}
Не понял, где смотреть красный знак "стоп"

2022-03-31 16:53 UTC, DenMazila commented on src/main/java/com/github/denmazila/java_learning/java_learning.iml
> +<?xml version="1.0" encoding="UTF-8"?>
добавил

2022-03-31 17:02 UTC, DenMazila commented on src/main/java/com/github/denmazila/java_learning/acmp/task0013/Main.java
> +                + " " + numberOfIndirectMatches(Main.integerToArrayConversionHiddenNumber(hiddenNumber), integerToArrayConversionSuggestedTumber(suggestedTumber)));
сделал

2022-03-31 18:55 UTC, vladimirshefer approved these changes

2022-03-31 18:56 UTC, merged